### ISSUE TITLE
Unable to install Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by prshnth** [rxaviers/cldr-data-npm#25]
abc <def> npm install globalize cldr-data
\
> cldr-data@28.0.2 install /usr/local/def/node_modules/cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/28.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/28.0.0.zip`
/usr/local/def/node_modules/cldr-data/node_modules/cldr-data-downloader/lib/download.js:51
      throw error;
      ^

Error: connect ETIMEDOUT 
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
npm ERR! Linux 2.6.18
npm ERR! argv "/usr/local/tde/acc/install/node/bin/node" "/usr/local/web/acc/install/node/bin/npm" "install" "globalize" "cldr-data"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! cldr-data@28.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@28.0.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/def/npm-debug.log

**Comment by prshnth** [comment]
@rxaviers I am stuck at the above issue, do you have any suggestions?!

**Comment by prshnth** [comment]
Never mind, its working.
