### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by NingenJanai** [rxaviers/cldr-data-npm#48]
I've been trying to install it all day with no luck.

When running: npm install --save cldr-data

I'm getting the following error:

GET `https://github.com/unicode-cldr/cldr-core/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/31.0.1.zip`
  [----------------------------------------] 28408146/Infinity 0% 0.0sC:\PROJECTS\ANXI\node_modules\cldr-data-downloader\lib\download.js:51
      throw error;
      ^

Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by NingenJanai** [comment]
It's still not working after a few days...

**Comment by NingenJanai** [comment]
It was a problem with my internet connection. I'm closing the issue.
