### ISSUE TITLE
Can not npm install on node@v8.1.4

### ISSUE THREAD

**Issue by sutiwo** [rxaviers/cldr-data-npm#49]
on node@v8.1.4 is failed.

```
$ npm install cldr-data --save

> cldr-data@31.0.2 install /Users/hoge/node_modules/cldr-data
> node install.js

Whops {} deepEqual { url:
   [ 'https://github.com/unicode-cldr/cldr-core/archive/31.0.1.zip',
     'https://github.com/unicode-cldr/cldr-dates-mo
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cldr-data@31.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@31.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

However, on node@6.9.4 is success.

```
$ npm install cldr-data --save
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> cldr-data@31.0.2 install /Users/hoge/node_modules/cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/31.0.1.zip`
  [========================================] 254637/0 100% 0.0s
Received 30967K total.
Unpacking it into `./`
+ cldr-data@31.0.2
added 13 packages in 32.618s
```

**Comment by jmeirelesfood** [comment]
Same here.

``` 
npm verb stack Error: cldr-data@27.0.10 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:887:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npm verb pkgid cldr-data@27.0.10
npm verb cwd /home/js/test
npm verb Linux 3.13.0-128-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v8.0.0
npm verb npm  v5.1.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cldr-data@27.0.10 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cldr-data@27.0.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

```

```
$ node -v
v8.0.0
$ npm -v
5.1.0

```

**Comment by jzaefferer** [comment]
Closer to the source: https://github.com/rxaviers/cldr-data-downloader/issues/24

**Comment by ubreddy** [comment]
Getting stuck on npm install cldr-data

node version 11.5.0
npm version 6.7.0

![image](https://user-images.githubusercontent.com/2233628/69161364-0980b180-0b11-11ea-8d4a-9510eadffc6e.png)
