### ISSUE TITLE
cldr-data installation issue

### ISSUE THREAD

**Issue by msreddy09** [rxaviers/cldr-data-npm#50]
I am able to install cldr-data 26.x module with out any error. But I am getting following error while installing latest version 31.x

``` 
throw error;
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

please do needful.

**Comment by rxaviers** [comment]
It works for me, please could you double check and let me know? Thanks.

**Comment by msreddy09** [comment]
Yes, it is working in another machine. But not working fine in my machine.
