### ISSUE TITLE
Webpack issue with cldr-data latest version

### ISSUE THREAD

**Issue by msreddy09** [rxaviers/cldr-data-npm#51]
As I am using react-globalize, it is using  cldr-data latest version.
With latest version I am getting following error while bundling with webpack.

I dont see **cldr-data\supplemental** folder in latest version. May I know how to work with latest version. When I am using cldr-data 26.x version, its working as expected.
```
C:\view\reactapp\node_modules\webpack\bin\webpack.js:323
                throw e;
                ^

Error: ENOENT: no such file or directory, scandir 'C:\view\reactapp\node_modules\cldr-data\supplemental'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at jsonFiles (C:\view\reactapp\node_modules\cldr-data\index.js:36:22)
    at supplementalPaths (C:\view\reactapp\node_modules\cldr-data\index.js:69:27)
    at Function.cldrData.entireSupplemental (C:\view\reactapp\node_modules\cldr-data\index.js:94:29)
    at cldr (C:\view\reactapp\node_modules\globalize-webpack-plugin\util.js:21:21)
    at new DevelopmentModePlugin (C:\view\reactapp\node_modules\globalize-webpack-plugin\DevelopmentModePlugin.js:27:40)
    at GlobalizePlugin.apply (C:\view\reactapp\node_modules\globalize-webpack-plugin\index.js:25:7)
    at Compiler.apply (C:\view\reactapp\node_modules\tapable\lib\Tapable.js:306:16)
    at webpack (C:\view\reactapp\node_modules\webpack\lib\webpack.js:32:19)
    at processOptions (C:\view\reactapp\node_modules\webpack\bin\webpack.js:313:14)
    at Object.<anonymous> (C:\view\reactapp\node_modules\webpack\bin\webpack.js:373:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
error Command failed with exit code 1.
```

**Comment by msreddy09** [comment]
Could you help me on this. Thanks

**Comment by rxaviers** [comment]
Please, does this still apply to you? Or was it an intermittent issue?

**Comment by KlavierCat** [comment]
Ran into this error too with webpack but after running `npm install cldr-data` manually I was able to bypass this.

**Comment by Cakmakk** [comment]
I ran into the same issue and I tried "npm install cldr-data" but I get still the same error. version 36.0.0

**Comment by sanjayror** [comment]
I'm having the same issue.

![image](https://user-images.githubusercontent.com/15170372/89708327-d2e71180-d993-11ea-90a6-eefeb9a19fb0.png)

when npm run build

**Comment by howlettt** [comment]
Ran into this issue as well, I had to uninstall a npm package that has cldr-data as a peer dependency first and then install cldr-data manually
