### ISSUE TITLE
During npm install: Error: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by olegdulin** [rxaviers/cldr-data-npm#52]
I am behind a proxy, and using cntlm, and I am getting this error. Tried various things, can't figure this out for the life of me. Outside of proxy this works. Here is the error:

```
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/31.0.1.zip`
./cldr-data-downloader/lib/download.js:119
      throw error;
      ^

Error: tunneling socket could not be established, cause=read ECONNRESET
    at ClientRequest.onError (/Users/dulino/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rxaviers** [comment]
A workaround would be fetching the files yourself, than having cldr-data to point to them using `file://` protocol. https://github.com/rxaviers/cldr-data-downloader/issues/25

**Comment by rxaviers** [comment]
At this moment, I think this is a wont-fix. If you have different ideas I'd be happy to reopen. Thanks
