### ISSUE TITLE
Install fails on step "node install.js"

### ISSUE THREAD

**Issue by k-vekos** [rxaviers/cldr-data-npm#53]
Output from npm log:

```
4395 verbose stack Error: cldr-data@32.0.0 install: `node install.js`
4395 verbose stack Exit status 1
4395 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
4395 verbose stack     at emitTwo (events.js:106:13)
4395 verbose stack     at EventEmitter.emit (events.js:194:7)
4395 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
4395 verbose stack     at emitTwo (events.js:106:13)
4395 verbose stack     at ChildProcess.emit (events.js:194:7)
4395 verbose stack     at maybeClose (internal/child_process.js:899:16)
4395 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
4396 verbose pkgid cldr-data@32.0.0
```

I thought it might be related to #24 but it's not the same error and I even tried rolling back to Node 7.0 but no luck.

node = v7.10.1
npm = 4.2.0

**Comment by hanqiangfei** [comment]
The same issue:
\node_modules\cldr-data-downloader\lib\download.js:119
      throw error;
      ^
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)

$ node -v
v10.12.0
$ npm -v
6.9.0

**Comment by suragar** [comment]
Is there any update on the above error?
